### ISSUE TITLE
Defining multiple signatures for different events and callbacks

### ISSUE THREAD

**Issue by Rochet2** [Foereaper/LuaLS-Eluna-Parser#1]
https://github.com/LuaLS/lua-language-server/issues/1456

**Comment by Foereaper** [comment]
Partially solved here https://github.com/LuaLS/lua-language-server/issues/2368, though still missing some functionality like variable function signature depending on event ID.

**Comment by Foereaper** [comment]
Implemented here https://github.com/Foereaper/LuaLS-Eluna-Parser/commit/f79289fe801eb3f8b3e42112a4bf83475ea6edfa

Requires the remaining Eluna method documentation to be updated similarly to https://github.com/ElunaLuaEngine/Eluna/commit/e3c8b127dd6bcd46014994c0ff46691a90aeae93

Should automatically parse all Register* methods once the documentation is updated

**Comment by Foereaper** [comment]
Fully supported as of https://github.com/ElunaLuaEngine/Eluna/commit/0a9066c8ce19c6ca4a2f5ba1d96bbaef5e1143fe
